<script setup>
import SectionFullScreen from '@/components/SectionFullScreen.vue'
import CardBox from '@/components/CardBox.vue'
import BaseButton from '@/components/BaseButton.vue'
import BaseButtons from '@/components/BaseButtons.vue'

</script>

<template>
  <SectionFullScreen
    v-slot="{ cardClass, cardRounded }"
    bg="login"
  >
    <CardBox
      :class="[cardClass, 'text-center p-10']"
      :rounded="cardRounded"
      form
      @submit.prevent="submit"
    >

      <h2 class="text-2xl mb-5">
        Welcome to your DEV.TO app!
      </h2>
      <p class="mb-5">
        This is Vue/nodejs2 app generated by the <a class="text-blue-500 hover:text-blue-600 active:text-blue-700" href="https://flatlogic.com/generator">Flatlogic Web App Generator</a> For guides and documentation please check
        your local README.md and <a class="text-blue-500 hover:text-blue-600 active:text-blue-700" href="https://flatlogic.com/documentation">Flatlogic documentation</a>
      </p>

      <BaseButtons class="justify-center mb-4">
        <BaseButton
          to="/login"
          color="default"
          label="Login"
          full
        />
      </BaseButtons>

      <ul class="flex justify-center flex-wrap md:justify-between">
        <li>
          <a class="text-blue-500 hover:text-blue-600 active:text-blue-700 pr-4 md:p-0" href="https://vuejs.org/">Vue.js</a>
        </li>
        <li>
          <a class="text-blue-500 hover:text-blue-600 active:text-blue-700 pr-4 md:p-0" href="https://nodejs.org/en/">Node.js</a>
        </li>
        <li>
          <a class="text-blue-500 hover:text-blue-600 active:text-blue-700 pr-4 md:p-0" href="https://flatlogic.com/forum">Flatlogic Forum</a>
        </li>
        <li>
          <a class="text-blue-500 hover:text-blue-600 active:text-blue-700" href="https://tailwindcss.com/">Tailwind</a>
        </li>
      </ul>
    </CardBox>
  </SectionFullScreen>
</template>
